package com.fimi.soul.drone.p107c;

/* renamed from: com.fimi.soul.drone.c.d */
enum C1472d {
    MILINK_PARSE_STATE_GOT_COMPID,
    MILINK_PARSE_STATE_UNINIT,
    MILINK_PARSE_STATE_IDLE,
    MILINK_PARSE_STATE_GOT_STX,
    MILINK_PARSE_STATE_GOT_LENGTH,
    MILINK_PARSE_STATE_GOT_MSGID,
    MILINK_PARSE_STATE_GOT_CRC1,
    MILINK_PARSE_STATE_GOT_PAYLOAD
}
